language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t sudhir/docker-react -f Dockerfile.dev .

script:
  - docker run sudhir/docker-react npm run test -- --coverage